# Site Settings
title: Adirtha Borgohain | AI @ Aqxle
name: Adirtha Borgohain
job_title: AI @ Aqxle 
email: adirthaborgohain@gmail.com
phone: "+91-8723912165"
description: >-
  I'm currently working on AI at Aqxle, building AI agents that help cut through marketing complexity, turning time-consuming analysis into fast, actionable insights.
  
  Over the years, I’ve worked across healthcare, cybersecurity, and now marketing tech - always staying close to the code. Whether it's building scalable systems, training models, or figuring out the right abstractions, I enjoy working at the intersection of applied ML and product impact.
  
  I’ve led and built projects from the ground up involving LLMs, data pipelines, and real-time systems, and more. I pick up new tools fast and care deeply about clean design and practical problem-solving.
  
  If you're working on something interesting or just want to chat about AI, feel free to reach out.

# Social Media
github_username: AdirthaBorgohain
linkedin_username: adirtha-borgohain

# Build settings
theme: null
plugins:
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md